256 pbr material textures vulkan
chaoticbob/GraphicsExperiments pull request #14
Opened 2023-06-02 05:23 UTC by loosche

Experiment now works on Vulkan

2023-06-02 23:29 UTC, chaoticbob requested changes
Mouse smoothing is missing from this sample.

2023-06-03 04:37 UTC, loosche commented
> Mouse smoothing is missing from this sample.

I'm not sure what you mean. The MouseMove() function seems the same as experiment 255, and the line regarding smoothing:

```
// Smooth out the rotation on Y
gAngle += (gTargetAngle - gAngle) * 0.1f;
```

Seems to be the same in both 255 and 256. Could you be more specific what code is missing?

2023-06-03 14:06 UTC, chaoticbob commented
> > Mouse smoothing is missing from this sample.
> 
> I'm not sure what you mean. The MouseMove() function seems the same as experiment 255, and the line regarding smoothing:
> 
> ```
> // Smooth out the rotation on Y
> gAngle += (gTargetAngle - gAngle) * 0.1f;
> ```
> 
> Seems to be the same in both 255 and 256. Could you be more specific what code is missing?

If you run both samples and compare the mouse move input. 255 feels a lot smoother when you rotate the camera. I don't know what could be happening in 256 it feels much less smooth as if the value is directly set instead of interpolated.

2023-06-05 00:42 UTC, chaoticbob approved these changes

2023-06-05 00:43 UTC, merged