403 gltf basic material metal
chaoticbob/GraphicsExperiments pull request #76
Opened 2024-02-07 06:24 UTC by loosche

Porting experiment 403 to Vulkan

2024-02-07 18:04 UTC, chaoticbob requested changes

2024-02-07 18:04 UTC, chaoticbob commented on projects/io/403_gltf_basic_material_metal/403_gltf_basic_material_metal.cpp
> +    auto window = Window::Create(gWindowWidth, gWindowHeight, "403_gltf_basic_material_metal");
Can this use the new macro?

2024-02-08 06:49 UTC, loosche commented on projects/io/403_gltf_basic_material_metal/403_gltf_basic_material_metal.cpp
> +    auto window = Window::Create(gWindowWidth, gWindowHeight, "403_gltf_basic_material_metal");
Use-ed!

2024-02-08 06:55 UTC, chaoticbob approved these changes

2024-02-09 03:20 UTC, merged